### ISSUE TITLE
Cannot copy the addons folder and it's subfolders into the www-root folder /var/www/

### ISSUE THREAD

**Issue by psy501** [Stephanowicz/moOde-audioplayer-addons#1]
I can't copy the file, i have an invalid permission error. I'm connected via ssh, using winscp sftp protocol. Have you an idea ?
![Capture d'écran 2024-12-05 220036](https://github.com/user-attachments/assets/460a45f8-2498-4b7c-8f8e-7602d56a4e81)

Insufficient permission
Error code: 3
Server error message: Permission denied

**Comment by Stephanowicz** [comment]
Hi,

with SFTP You need 2 additional settings for the **connection** of WinSCP:
in the "extended" settings menue (I don't know the exact spelling in english/french - hope You know what I mean : ) )
there are to categories:  
  
1. SFTP --> SFTP-Server:    **sudo /usr/lib/sftp-server**   
2. SHELL --> Shell:   **sudo su -**    

Hope this helps!

Cheers, Stephan

**Comment by psy501** [comment]
Thanks you 🥰 

It works perfectly, thanks for this great pack of addons for moodeaudio. I hope it will be hard-integrated into moodeaudio soon, like the volumio add-ons, it would make the installation easier

**Comment by Stephanowicz** [comment]
Welcome  and thank You :)

**Comment by psy501** [comment]
The addons seem to work, the system has become a little slower, I am on raspberry 4. Before when I press on the cover it was in large, now it puts me the library, do you have any idea why?

**Comment by Stephanowicz** [comment]
Hi.
Ok, I need to look into that the next days - maybe there was a change in the default action for the albumcover in some version update.   
If You disable the 'Multialbumart' option it should behave like usual  ( though I wonder how You can get then to the library..?)  
   
Cheers, Stephan

**Comment by Stephanowicz** [comment]
Hi,
so I looked into the moode-source and I couldn't find anything that would display a large cover...
Sorry, are You sure You had this with moOde player - or maybe volumio has this option? :)

**Comment by psy501** [comment]
This may have nothing to do with your Addon but when I press on the cover, before I had the coverview, now I have the radio browser or music folder if I listen to another music![2024-12-06-20-27-52-991.jpg](https://github.com/user-attachments/assets/b84f35f5-92cd-4a8f-b727-3afeaec2c945)

![2024-12-06-20-27-58-948.jpg](https://github.com/user-attachments/assets/ef5f5603-183c-4e03-97c4-c4c91da5d245)

**Comment by Stephanowicz** [comment]
Ok, I misunderstood You - You meant the screensaver or coverview.    
Well, I only know it like that, when clicking on the cover You switch to the library.   
For switching to the coverview, You normally use the icon which looks like a display   
![image](https://github.com/user-attachments/assets/0d929040-91de-405b-984b-e260c592cca3)   
But Your screen aspect ratio is so wide, that You can't see the buttons in normal view - in the library view, You can see them   
So, honestly I have no clue, how You could switch to the coverview by clicking on the cover

**Comment by psy501** [comment]
Ok thanks, i have this icon ![2024-12-06-22-56-14-751.jpg](https://github.com/user-attachments/assets/c40c2316-3db2-409c-97ac-367976a2ba59)

**Comment by Stephanowicz** [comment]
Ok, this is in Coverview - You mean when You now click on the cover You are directed to the library?
I can check this tomorrow. My player is already sleepig :)  
I only remember when You were in the library and switched directly to the coverview, then, when clicking on the bottom bar, You are switching back to the library - maybe this is also the behaviour when clicking on the cover - I will see tomorrow :)

**Comment by psy501** [comment]
I would like to have the cover view by clicking on the cover, too bad if it is not possible 😞🫣

**Comment by Stephanowicz** [comment]
Well, one could change the action when clicking on the cover - but then one would need an additional option to switch to the library, as this is the only way afaik to get there...

**Comment by psy501** [comment]
Ok 🤪 thanks for your help 🥰🥰

**Comment by Stephanowicz** [comment]
Hey,   
As Your screen is very wide the buttons below the playcontrol move out of sight...
would it be ok, if You had the usual buttons below the playcontrol?  
This would also include the button for switching to coverview.  

Then it should look like this:  
![image](https://github.com/user-attachments/assets/a68d683e-c1f0-4856-8ce1-b5f154af47d6)

**Comment by psy501** [comment]
Yes indeed, that would be perfect, but how to do that?

**Comment by Stephanowicz** [comment]
Ok, two possibilities:  

1. I could try to extend the css declarations for this screen width/height...   

2. The better solution would be to open an issue at [moode audio](https://github.com/moode-player/moode/issues)   
then it could be integrated in their source and is available for all that have this kind of screens

(I'm not sure, but I think I've already seen a discussion about this...)

Can You give me details of Your screen? The resolution would be important to know - or, if You don't know, the name/type of the display

**Comment by psy501** [comment]
It's an waveshare screen

11.9inch Capacitive Touch Screen LCD, 320×1480, HDMI, IPS, Toughened Glass Cover

https://www.waveshare.com/wiki/11.9inch_HDMI_LCD

**Comment by Stephanowicz** [comment]
Ok, thank You   

I'll take a look at it and see what I can do :)

**Comment by Stephanowicz** [comment]
Yo,  
I got it!  

This is how the main screen looks like originally with 1480x320:  
![image](https://github.com/user-attachments/assets/4b01de58-3c23-4462-9749-c05a72d8ea8b)

and this is how it looks with the fix:  
![image](https://github.com/user-attachments/assets/1fa64085-8ec3-4b3b-9fe9-1f7b61cb9e8f)

You need to download the latest: [v1.0.11](https://github.com/Stephanowicz/moOde-audioplayer-addons/releases/tag/v1.0.11)

Cheers,

Stephan

**Comment by Stephanowicz** [comment]
PS: started an issue: [https://github.com/moode-player/moode/issues/696](https://github.com/moode-player/moode/issues/696)

**Comment by Stephanowicz** [comment]
A bit confusing, that some messages seem to link to the moode thread - or I was to tired and confused it :D  

Ok, great that You've got it know!  

Meanwhile I made some changes to the script as I followed Tim Curtis' suggestion and using the moode/media.css structure.  
If You don't mind could You please test it? 
You can download the file here: [script.js](https://github.com/Stephanowicz/moOde-audioplayer-addons/blob/master/addons/Stephanowicz/script.js)  

Before copying I would rename Your file on moode player to smth like script._js  so You can restore it in case it does not work.  

If it's not working properly it would be helpful to get the 'real' resolution of Your screen - the size of the page being displayed - I could make a test page that shows the window metrics  

Cheers, Stephan

**Comment by Stephanowicz** [comment]
Here is the code for getting the window metrics:   
  

```
<!DOCTYPE html>
<html>
<body>

<p id="screen"></p>
<p id="screenavail"></p>
<p id="windowOuter"></p>
<p id="windowInner"></p>

<script>
document.getElementById("screen").innerHTML = 
"screen width is " + screen.width + "<br>"+
"screen height is " + screen.height;
document.getElementById("screenavail").innerHTML = 
"available screen width is " + screen.availWidth + "<br>"+
"available screen height is " + screen.availHeight;
document.getElementById("windowOuter").innerHTML = 
"window outer width is " + window.outerWidth + "<br>"+
"window outer height is " + window.outerHeight;
document.getElementById("windowInner").innerHTML = 
"window inner width is " + window.innerWidth + "<br>"+
"window inner height is " + window.innerHeight;
</script>

</body>
</html>
```   
   

  
You can duplicate the **config.html** and change the content with this - then You can open it in the **m**oode menue --> "Addons configuration"

**Comment by psy501** [comment]
I have test it but i have no music listing of the size. With the config.html modif i have this result 

![Capture d'écran 2024-12-08 190143](https://github.com/user-attachments/assets/c88dae93-f07f-4d99-9ce0-a0537ebeede0)

**Comment by Stephanowicz** [comment]
Thank You that You tried it.
These values don't make sense :D Maybe one has to open the file directly and not embedded in moode player.

I asked for them because I wanted to simulate Your display - as the first try didn't work I wanted to know the metrics to get a good result.

Ok, as long as You have a working solution now...let's leave it be

Cheers, Stephan

Btw - nice case You have - my display is still standing around bare :D

**Comment by psy501** [comment]
Special thanks to you

Indeed the height values are very strange for a screen with a resolution of 1480*320, but thanks to you it works correctly. 

The case is a GX388 from modushop, I cut it myself with a cnc milling machine. 

Have a nice evening
Alexis
![2024-12-09-17-36-37-775](https://github.com/user-attachments/assets/abca86df-c310-414a-bb78-99cf799aacd2)

**Comment by Stephanowicz** [comment]
Wow, nice!

Yes, I'm also planning to do smth in this direction - but maybe not to this extend - not sure yet e.g. the power supply.

Thx for sharing!

Cheers, Stephan
