### ISSUE TITLE
no Addons option appears in main menu

### ISSUE THREAD

**Issue by githubsubx** [Stephanowicz/moOde-audioplayer-addons#2]
Help, I'm not getting any of the addons to appear. I am running the very latest 9.1.50202411-26 version.

I am new to everything here (I'm not a programmer or know much about scripting) I had major difficulties copying the addons files to /var/www but have followed and painstakingly teased out how to do all except the following: (btw where and how are these files located and accessed?)

"Generally You need to add a link to addons.js in header.php
-> below the  section in header.php You should find a link to lib.min.js: <script src="js/lib.min.js?t=1729607710734" defer></script>
after this add <script src="addons/addons.js?t=1729607710734" defer></script>
(the t=xxxx can be different - you may copy the one from lib.min.js)"

Is this the reason why no Adddons Configuration menu option appears in my drop down menu?

Note when I interrogate everything via the URL to the config-page (http://xxx.local/addons/Stephanowicz/config.html) all is validated ok. 

Can anyone help?

**Comment by githubsubx** [comment]
Hi I've managed to sort the above 👍 . Thanks

**Comment by Stephanowicz** [comment]
PS: Added the complete path to the readme
`/var/www/header.php`
