### ISSUE TITLE
 No Lyrics - "cannot parse the lyrics-page" error message  

### ISSUE THREAD

**Issue by githubsubx** [Stephanowicz/moOde-audioplayer-addons#3]
I cannot get any lyrics to display irrespective of whichever browser I use. 
![Capture](https://github.com/user-attachments/assets/0822d93f-81b3-4f23-a99b-a29da2454c7d)

**Comment by Stephanowicz** [comment]
Hi,

thank You - seems like they changed smth... this happens from time to time

A fix is available in the last release v1.0.12
